[package]
name = "capture-dn"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
poise = "0.6.1"
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }

[dependencies.diesel]
version = "2.1.4"
features = ["chrono", "postgres", "r2d2"]
default-features = false
