name: Build

on:
  push:
    branches: [main]
    paths: ["src/**", "Cargo.*", "flake.*"]
  pull_request:
    paths: ["src/**", "Cargo.*", "flake.*"]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: "nekowinston"

      - name: Flake check
        run: nix flake check

      - name: Build package
        run: nix build -L .
