# SPDX-FileCopyrightText: 2024 winston <hey@winston.sh>
# SPDX-License-Identifier: CC0-1.0

name: Devenv

on:
  push:
    branches:
      - main
    paths: 
      - "src/**"
      - "*.lock"
      - "*.nix"
  pull_request:
    paths:
      - "src/**"
      - "*.lock"
      - "*.nix"

jobs:
  devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv test
