# SPDX-FileCopyrightText: 2024 winston <hey@winston.sh>
# SPDX-License-Identifier: CC0-1.0

name: Devenv

on:
  push:
    branches:
      - main
    paths: 
      - "src/**"
      - "*.lock"
      - "*.nix"
  pull_request:
    paths:
      - "src/**"
      - "*.lock"
      - "*.nix"

jobs:
  devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv test
