name: Nix Build

on:
  push:
    branches: [main]
    paths: ["src/**", "Cargo.*", "flake.*"]
  pull_request:
    paths: ["src/**", "Cargo.*", "flake.*"]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # TODO: add Cachix step

      - name: Check
        run: nix flake check --impure

      - name: Build package
        run: nix build -Lv .
